apiVersion: apps/v1
kind: Deployment
metadata:
  name: uber-deployment
spec:
  replicas: 3  # Number of desired replicas
  selector:
    matchLabels:
      app: uber
  template:
    metadata:
      labels:
        app: uber
    spec:
      containers:
      - name: uber
        image: avinashbudhya/uber:latest
        ports:
        - containerPort: 3000  # Port your application listens on

